### PR TITLE
Add more extensions to dotenv apps

### PR DESCRIPTION
**Pull request by diegorv**
This PR adds new extensions that are used by `dotenv applications` like https://github.com/bkeepers/dotenv

### CODE REVIEW

**Comment by mattbanks** [comment]
👍  Can you also add them to the readme @diegorv?

**Comment by diegorv** [comment]
Sorry @mattbanks.

Done! :)

**Comment by mattbanks** [comment]
tkypabkdwj4ts

**Comment by diegorv** [comment]
<3 <3 <3

**Pull request merged**
